common:
  batch_size: 256

classification:
  epochs: 200
  lr: 5e-4
  weight_decay: 1e-5
  models:
    LSTM:
      hidden_size: 128
      dropout: 0.9
    GRU:
      hidden_size: 128
      dropout: 0.9
    DLinear:
      dropout: 0.2
    Transformer:
      hidden_size: 64
      dropout: 0.5
    RandomForest:
      max_depth: 7
    GradientBoosting:
      max_depth: 7

regression:
  epochs: 100
  lr: 1e-3
  weight_decay: 1e-4